<h1><center>Lecture - 1</center></h1>

##### Library Imports

In [1]:
import numpy as np

####  Ax=b   =>   Multiplication as linear combination of columns 

In [2]:
# Defining function for multiplication
def linear_combination_product(A,x):
    prod = np.zeros((A.shape[0],x.shape[1]))
    if(A.shape[1] == x.shape[0]): # Dimension criteria
        for j in range(x.shape[1]): # For all columns in x
            temp = np.zeros((x.shape[0],1)) # To calculate linear combination of columns of A with coefficients x[:,j]
            for i in range(x.shape[0]): # For all rows in x[:,j] OR for all coulmns in A
                temp = temp + (x[i,j]*A[:,i]).reshape(A.shape[0],1) # Calculated matrix of size x.shape[0] is added
            prod[0:,j] = temp[:,0] # after each column in x, value is assigned to prod matxix (Filled column by column)
        return prod
    else:
        return 0 # Return 0 as product not possible


#### Examples:

In [3]:
# Example - 1

A = np.array([[1,5,7],[3,5,2],[3,7,1]])
x = np.array([[3,2],[2,4],[1,6]])

# Calling function        
prod = linear_combination_product(A,x)
print(A)
print(x)
print(prod)

[[1 5 7]
 [3 5 2]
 [3 7 1]]
[[3 2]
 [2 4]
 [1 6]]
[[20. 64.]
 [21. 38.]
 [24. 40.]]


In [4]:
# Example - 2

A = np.random.randint(10,size=(3,3))
x = np.random.randint(10,size=(3,8))


# Calling function        
prod = linear_combination_product(A,x)
print(A)
print(x)
print(prod)

[[9 2 8]
 [2 8 3]
 [2 9 7]]
[[3 1 4 6 0 0 1 0]
 [2 8 7 5 6 5 1 4]
 [0 9 9 4 8 8 6 8]]
[[ 31.  97. 122.  96.  76.  74.  59.  72.]
 [ 22.  93.  91.  64.  72.  64.  28.  56.]
 [ 24. 137. 134.  85. 110. 101.  53.  92.]]
